# Generated by Django 6.0 on 2026-01-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogapp", "0016_remove_avatar_user_remove_order_products_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[
                            ("free", "Бесплатная доставка"),
                            ("paid", "Платная доставка"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        choices=[("online", "Онлайн"), ("cash", "Наличными")],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(decimal_places=2, max_digits=1000000000),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("not accepted", "Not Accepted"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=70)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="orders", to="catalogapp.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
