# Generated by Django 6.0 on 2026-01-19 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                999999999999999, "15 цифр"
                            )
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                2000, "Год от 2000"
                            ),
                            django.core.validators.MaxValueValidator(
                                2099, "Год до 2099"
                            ),
                        ]
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]{3}$")
                        ],
                    ),
                ),
            ],
        ),
    ]
