# Generated by Django 6.0 on 2025-12-26 15:02

import catalogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=catalogapp.models.gen_path_to_avatar),
                ),
                ("alt", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
