# Generated by Django 6.0 on 2025-12-27 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0003_avatar_user_alter_avatar_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(max_length=15)),
                ("name", models.CharField(max_length=35)),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                2000, "Год от 2000"
                            ),
                            django.core.validators.MaxValueValidator(
                                2099, "Год до 2099"
                            ),
                        ]
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]{3}$")
                        ],
                    ),
                ),
            ],
        ),
    ]
