# Generated by Django 6.0 on 2025-12-30 16:08

import catalogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0009_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
            ),
        ),
    ]
