# Generated by Django 6.0 on 2025-12-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0010_alter_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(
                null=True, related_name="products", to="catalogapp.review"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="products", to="catalogapp.tag"
            ),
        ),
    ]
