# Generated by Django 6.0 on 2026-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0013_product_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("value", models.CharField(max_length=70)),
            ],
        ),
    ]
