# Generated by Django 6.0 on 2026-01-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0014_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="specifications",
            name="products",
            field=models.ManyToManyField(
                related_name="specifications", to="catalogapp.product"
            ),
        ),
    ]
