# Generated by Django 6.0 on 2026-01-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0015_specifications_products"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avatar",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="review",
            name="author",
        ),
        migrations.AlterField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="reviews.review"
            ),
        ),
        migrations.DeleteModel(
            name="Avatar",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
