# Generated by Django 6.0 on 2025-12-29 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(999999999999999, "15 цифр")
                ]
            ),
        ),
    ]
