# Generated by Django 6.0 on 2025-12-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0011_alter_product_reviews_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="shopapp.review"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="shopapp.tag"
            ),
        ),
    ]
