# Generated by Django 6.0 on 2026-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0012_alter_product_reviews_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
